name: Create VPC Endpoint Infra

on:
  workflow_dispatch:

jobs:
  create-vpc-endpoint-infra:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      #AWS CREDENTIALS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION}}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: myGitHubActions
      #Terraform execution
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply Destroy
        run: terraform apply -auto-approve
        env:
          TF_VAR_vpc_id: ${{ vars.VPC_ID }}
          TF_VAR_subnet_a: ${{ vars.SUBNET_A }}
          TF_VAR_subnet_b: ${{ vars.SUBNET_B }}
          TF_VAR_sg_cluster_ecs: ${{ vars.SG_CLUSTER_ECS }}
          TF_VAR_rt_subnet_a: ${{ vars.RT_SUBNET_A }}
          TF_VAR_rt_subnet_b: ${{ vars.RT_SUBNET_B }}