name: Destroy VPC Endpoint Infra

on:
  workflow_dispatch:

jobs:
  destroy-vpc-endpoint-infra:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      #AWS CREDENTIALS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      #Terraform execution
      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run:  terraform destroy -auto-approve
        env:
          TF_VAR_vpc_id: ${{ vars.VPC_ID }}
          TF_VAR_subnet_a: ${{ vars.SUBNET_A }}
          TF_VAR_subnet_b: ${{ vars.SUBNET_B }}
          TF_VAR_sg_cluster_ecs: ${{ vars.SG_CLUSTER_ECS }}
          TF_VAR_rt_subnet_a: ${{ vars.RT_SUBNET_A }}
          TF_VAR_rt_subnet_b: ${{ vars.RT_SUBNET_B }}